version: '3.5'

networks:
  localdev:
    name: localdev

services:
  microservice:
    image: microservice-kube-app
    build:
      context: .
      dockerfile: Src/MicroService/Dockerfile
    restart: always
    ports:
      - "44400:443"
    depends_on:
      - db-server
    networks:
      - localdev

  db-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
      - MSSQL_TCP_PORT=1433
    ports:
      - "1400:1433"
    networks:
      - localdev