apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-kube-app-deployment
spec:
  selector:
    matchLabels:
      app: microservice-kube-app
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-kube-app
    spec:
      containers:
        - image: "253347999681.dkr.ecr.ap-southeast-2.amazonaws.com/microservice-kube-app"
          imagePullPolicy: Always
          name: microservice-kube-app
          ports:
            - containerPort: 80
          env:
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              configMapKeyRef:
                name: mssql-connection-configmap
                key: db-connection-string
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-kube-app-service
spec:
  selector:
    app: microservice-kube-app
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: microservice-kube-app