apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: db-server
        image: mcr.microsoft.com/mssql/server:2019-latest
        #resources:
        #  limits:
        #    cpu: "1"
        #    memory: "1Gi"
        #  requests:
        #    cpu: "0.5"
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "1Secure*Password1"
        #volumeMounts:
        #- name: mssql
        #  mountPath: /var/opt/mssql
      #volumes:
      #- name: mssql
      #  persistentVolumeClaim:
      #    claimName: mssql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer